blank_issues_enabled: false
contact_links:
  - name: "🙏 Help & Questions"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: "GitHub Discussions: get official help from maintainers."
  - name: "🗨️ Other"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: "GitHub Discussions: ideas, feedback, complaints, appreciation, ..."
  - name: "💬 Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: "Discord: casual conversation with the community."
