name: 'Check formatting'
on:
  push:
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run format:check

